stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/portfoliopage:$CI_COMMIT_REF_SLUG
  CONTAINER_NAME: portfoliopage

build_app:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker images
    - docker push $IMAGE_TAG
  tags:
    - raspberry
    - home

deploy_container:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker-compose build
    - docker-compose up -d
  tags:
    - raspberry
    - home
